/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPER_H_RPCGEN
#define _OPER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct in1 {
	struct {
		u_int y_len;
		int *y_val;
	} y;
};
typedef struct in1 in1;

struct in2 {
	double a;
	struct {
		u_int y_len;
		int *y_val;
	} y;
};
typedef struct in2 in2;

struct out1 {
	int maxmin[2];
};
typedef struct out1 out1;

struct out2 {
	struct {
		u_int pr_len;
		double *pr_val;
	} pr;
};
typedef struct out2 out2;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AVG 1
extern  double * avg_1(in1 *, CLIENT *);
extern  double * avg_1_svc(in1 *, struct svc_req *);
#define MAXMIN 2
extern  out1 * maxmin_1(in1 *, CLIENT *);
extern  out1 * maxmin_1_svc(in1 *, struct svc_req *);
#define PRODay 3
extern  out2 * proday_1(in2 *, CLIENT *);
extern  out2 * proday_1_svc(in2 *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AVG 1
extern  double * avg_1();
extern  double * avg_1_svc();
#define MAXMIN 2
extern  out1 * maxmin_1();
extern  out1 * maxmin_1_svc();
#define PRODay 3
extern  out2 * proday_1();
extern  out2 * proday_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_in1 (XDR *, in1*);
extern  bool_t xdr_in2 (XDR *, in2*);
extern  bool_t xdr_out1 (XDR *, out1*);
extern  bool_t xdr_out2 (XDR *, out2*);

#else /* K&R C */
extern bool_t xdr_in1 ();
extern bool_t xdr_in2 ();
extern bool_t xdr_out1 ();
extern bool_t xdr_out2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPER_H_RPCGEN */
